[build]
  command = "npm ci && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 🔀 Redirecciones al backend (FastAPI en Railway/Render/etc.)
[[redirects]]
  from = "/backend/chat"
  to = "https://TU_BACKEND_URL/chat"
  status = 200
  force = true

[[redirects]]
  from = "/backend/tts"
  to = "https://TU_BACKEND_URL/tts"
  status = 200
  force = true

[[redirects]]
  from = "/backend/health"
  to = "https://TU_BACKEND_URL/ping"
  status = 200
  force = true
