[build]
  command = "npm ci && npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/solve"
  to = "${NEXT_PUBLIC_BACKEND_URL}${NEXT_PUBLIC_BACKEND_SOLVE_PATH}"
  status = 200
  force = true

# Salud
[[redirects]]
  from = "/api/health"
  to = "${NEXT_PUBLIC_BACKEND_URL}/ping"
  status = 200
  force = true
