[build]
  command = "next build"
  publish = ".next"

[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/tutorin.png"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
