[build]
  command = "npm ci && npm run build"
  publish = ".next"

# Proxy para resolver
[[redirects]]
  from = "/backend/solve"
  to   = "https://web-production-f480.up.railway.app/chat"
  status = 200
  force = true

# Comprobación de salud
[[redirects]]
  from = "/backend/health"
  to   = "https://web-production-f480.up.railway.app/ping"
  status = 200
  force = true
