[build]
  command = "npm ci && npm run build"
  publish = "out"

# 👇 Redirecciones para que el frontend hable con el backend
[[redirects]]
  from = "/backend/chat"
  to = "https://web-production-f480.up.railway.app/chat"
  status = 200
  force = true

[[redirects]]
  from = "/backend/tts"
  to = "hhttps://web-production-f480.up.railway.app/tts"
  status = 200
  force = true

[[redirects]]
  from = "/backend/health"
  to = "https://web-production-f480.up.railway.app/ping"
  status = 200
  force = true
